-- ================================================
-- ファイル名: 04_select_items_case_by_year.sql
-- 役割:
--   Items テーブルから商品名・年・価格を取得する際に、
--   年によって参照する価格列を CASE 式で切り替える。
--
-- このSQLの目的:
--   2001年以前は税抜価格 price_tax_ex を使い、
--   2002年以降は税込価格 price_tax_in を使って、
--   1本の SELECT 文で price 列を作ること。
--
-- 学習上の主題:
--   SELECT 句における CASE 式による条件分岐を理解すること。
--
-- 今回の最重要ポイント:
--   先ほどの UNION ALL 版は、
--     1. 前半SELECT
--     2. 後半SELECT
--   を別々に書いて最後に結合していた。
--
--   一方、今回の CASE 版は、
--   1本の SELECT の中で
--   「price に何を入れるか」
--   だけを条件で切り替えている。
--
--   つまり今回は、
--   集合を分けてから結合するのではなく、
--   各行ごとに price の値を決めている。
-- ================================================

SELECT
    item_name,
    -- item_name:
    --   商品名をそのまま表示する。
    --
    --   例:
    --     カップ
    --     スプーン
    --     ナイフ

    year,
    -- year:
    --   その価格がどの年のものかを表す。
    --
    --   今回の CASE 式では、
    --   この year の値を見て
    --   どちらの価格列を使うかを決める。

    CASE
        -- CASE 式:
        --   SQL の式の中で条件分岐を行うための構文である。
        --
        --   MySQL にはストアドプログラム用の CASE statement と、
        --   式として使う CASE operator があるが、
        --   今回 SELECT 句の中で使っているのは
        --   値を返す CASE 式の方である。  [oai_citation:0‡MySQL Developer Zone](https://dev.mysql.com/doc/refman/8.0/ja/flow-control-functions.html?utm_source=chatgpt.com)
        --
        --   つまり今回は、
        --   各行について year を見て
        --   price に入れる値を切り替えている。

        WHEN year <= 2001 THEN price_tax_ex
        -- year <= 2001:
        --   2000年と2001年の行では税抜価格を使う。
        --
        -- THEN price_tax_ex:
        --   条件が真なら、price_tax_ex の値を返す。
        --
        -- したがって
        --   2000年, 2001年 -> 税抜価格
        -- となる。

        WHEN year >= 2002 THEN price_tax_in
        -- year >= 2002:
        --   2002年と2003年の行では税込価格を使う。
        --
        -- THEN price_tax_in:
        --   条件が真なら、price_tax_in の値を返す。
        --
        -- したがって
        --   2002年, 2003年 -> 税込価格
        -- となる。

    END AS price
    -- END:
    --   CASE 式の終わりを表す。
    --
    -- AS price:
    --   CASE 式の結果列に price という名前を付ける。
    --
    --   元の列は
    --     price_tax_ex
    --     price_tax_in
    --   という2本だが、
    --   最終結果ではそれを1本の列 price として見せる。

FROM
    Items;
    -- FROM Items:
    --   Items テーブルを元データとして参照する。
    --
    --   今回は WHERE 句が無いため、
    --   Items の全行が対象になる。


-- ================================================
-- このSQLの処理の流れ
-- ================================================
--
-- 1. Items テーブルの全行を読む
-- 2. 各行について year の値を確認する
-- 3. year <= 2001 なら price_tax_ex を選ぶ
-- 4. year >= 2002 なら price_tax_in を選ぶ
-- 5. 選ばれた値を price 列として返す
--
-- 概念的には次のような処理に近い。
--
--   for each row in Items:
--       if row.year <= 2001:
--           price = row.price_tax_ex
--       elif row.year >= 2002:
--           price = row.price_tax_in
--
--       output row.item_name, row.year, price
--
-- つまりこれは、
--   「各行を1回ずつ見て、その行の year に応じて price を決める」
--   という列値分岐である。


-- ================================================
-- UNION ALL 版との違い
-- ================================================
--
-- 先ほどの UNION ALL 版は概念的に次のような構造だった。
--
--   前半:
--     year <= 2001 の行を取り、
--     price_tax_ex を price として返す
--
--   後半:
--     year >= 2002 の行を取り、
--     price_tax_in を price として返す
--
--   その後:
--     UNION ALL で2つの結果を縦結合する
--
-- これは
--   「集合を前半・後半に分けてから結合する」
-- 書き方である。
--
-- 一方、今回の CASE 版は
--   「行は最初から全部対象にして、
--     各行の price だけを条件で切り替える」
-- 書き方である。
--
-- つまり整理すると、
--
--   UNION ALL 版
--     → SELECT を2本に分ける
--     → 結果集合レベルの分岐
--
--   CASE 版
--     → SELECT は1本
--     → 列値レベルの分岐
--
-- という違いがある。


-- ================================================
-- パフォーマンス比較の考え方
-- ================================================
--
-- ここが今回の中心である。
--
-- 一般論として、この CASE 版は
--   同じテーブル Items に対する 1 本の SELECT
-- であるのに対し、
-- 先ほどの UNION ALL 版は
--   Items を読む 2 つの query block
-- から構成される。MySQL の UNION / set operations は
-- 複数の query block を組み合わせる構文である。  [oai_citation:1‡MySQL Developer Zone](https://dev.mysql.com/doc/en/union.html?utm_source=chatgpt.com)
--
-- そのため、
--   Items を同じ条件分岐のために 2 回読む形になりやすい UNION ALL 版より、
--   1 回の走査の中で列値だけを切り替える CASE 版の方が、
--   単純で有利になりやすい
-- と考えるのが自然である。これは実行計画から推測される一般的な見方である。  [oai_citation:2‡MySQL Developer Zone](https://dev.mysql.com/doc/en/union.html?utm_source=chatgpt.com)
--
-- ただし、実際の速さは
--   インデックス
--   行数
--   統計情報
--   最適化
-- などに依存するため、
--   必ず CASE 版が速い
-- と断定はできない。
--
-- したがって実務では、
--   EXPLAIN
-- で実行計画を確認して比較するのが正しい。EXPLAIN は
-- SELECT を含む文の実行方法を確認するための仕組みである。  [oai_citation:3‡MySQL Developer Zone](https://dev.mysql.com/doc/en/explain-output.html?utm_source=chatgpt.com)
--
-- 今回のように
--   同じ表
--   同じ出力列
--   年での単純な切り替え
-- という条件なら、
--   可読性・保守性・単純さの面でも
--   CASE 版の方が自然
-- であることが多い。これは上の構造差からの妥当な推論である。  [oai_citation:4‡MySQL Developer Zone](https://dev.mysql.com/doc/en/union.html?utm_source=chatgpt.com)


-- ================================================
-- 実行結果のイメージ
-- ================================================
--
-- Items に次のようなデータがあるとする。
--
--   item_name | year | price_tax_ex | price_tax_in
--   ----------+------+--------------+-------------
--   カップ    | 2000 | 500          | 525
--   カップ    | 2001 | 520          | 546
--   カップ    | 2002 | 600          | 630
--   カップ    | 2003 | 600          | 630
--
--   スプーン  | 2000 | 500          | 525
--   スプーン  | 2001 | 500          | 525
--   スプーン  | 2002 | 500          | 525
--   スプーン  | 2003 | 500          | 525
--
--   ナイフ    | 2000 | 600          | 630
--   ナイフ    | 2001 | 550          | 577
--   ナイフ    | 2002 | 550          | 577
--   ナイフ    | 2003 | 400          | 420
--
-- このとき CASE 式により、
--   2000, 2001 -> 税抜価格
--   2002, 2003 -> 税込価格
-- が選ばれる。
--
-- したがって最終結果は概ね次のようになる。
--
--   item_name | year | price
--   ----------+------+------
--   カップ    | 2000 | 500
--   カップ    | 2001 | 520
--   カップ    | 2002 | 630
--   カップ    | 2003 | 630
--   スプーン  | 2000 | 500
--   スプーン  | 2001 | 500
--   スプーン  | 2002 | 525
--   スプーン  | 2003 | 525
--   ナイフ    | 2000 | 600
--   ナイフ    | 2001 | 550
--   ナイフ    | 2002 | 577
--   ナイフ    | 2003 | 420
--
-- 結果自体は UNION ALL 版と同じ意味になるが、
-- 生成のしかたが違う。


-- ================================================
-- 図解: CASE 版と UNION ALL 版の比較
-- ================================================
--
-- 1. CASE 版
--
--   Items を 1 回読む
--        |
--        v
--   各行の year を判定
--        |
--        +------------------------------+
--        | year <= 2001 なら 税抜価格   |
--        | year >= 2002 なら 税込価格   |
--        +------------------------------+
--        |
--        v
--   item_name, year, price を返す
--
--
-- 2. UNION ALL 版
--
--   Items を読む(前半)
--        |
--        v
--   year <= 2001 の行だけ
--        |
--        v
--   税抜価格を返す
--
--   Items を読む(後半)
--        |
--        v
--   year >= 2002 の行だけ
--        |
--        v
--   税込価格を返す
--
--   前半結果
--      +
--   後半結果
--      |
--      v
--   UNION ALL で結合
--
-- つまり、
--   CASE 版 = 1本の SELECT の中で値分岐
--   UNION ALL 版 = 2本の SELECT に分けて結果結合
-- という違いである。


-- ================================================
-- 構文ごとの意味
-- ================================================
--
-- SELECT item_name, year, CASE ... END AS price
--   → item_name, year と、CASE で選んだ価格を返す
--
-- CASE
--   → 条件分岐で返す値を切り替える
--
-- WHEN year <= 2001 THEN price_tax_ex
--   → 2001年以前は税抜価格を返す
--
-- WHEN year >= 2002 THEN price_tax_in
--   → 2002年以降は税込価格を返す
--
-- END AS price
--   → CASE の結果列を price という名前で返す
--
-- FROM Items
--   → Items テーブルを元データとする
--
-- ;
--   → SQL文の終了を表す


-- ================================================
-- EXPLAIN で比較すべき理由
-- ================================================
--
-- MySQL の EXPLAIN は、
--   SELECT がどのように実行されるか
-- を確認するための仕組みである。  [oai_citation:5‡MySQL Developer Zone](https://dev.mysql.com/doc/en/explain-output.html?utm_source=chatgpt.com)
--
-- そのため、今回のように
--   CASE 版
--   UNION ALL 版
-- のどちらが有利かを判断したい場合は、
-- それぞれに EXPLAIN を付けて比較するのが正しい。
--
-- 例:
--
--   EXPLAIN
--   SELECT item_name, year,
--          CASE WHEN year <= 2001 THEN price_tax_ex
--               WHEN year >= 2002 THEN price_tax_in END AS price
--     FROM Items;
--
--   EXPLAIN
--   SELECT item_name, year, price_tax_ex AS price
--     FROM Items
--    WHERE year <= 2001
--   UNION ALL
--   SELECT item_name, year, price_tax_in AS price
--     FROM Items
--    WHERE year >= 2002;
--
-- この比較により、
--   何回テーブルを読むか
--   どんなアクセス方法か
-- などを確認できる。EXPLAIN は各テーブルをどう読むかを表示する。  [oai_citation:6‡MySQL Developer Zone](https://dev.mysql.com/doc/en/explain-output.html?utm_source=chatgpt.com)


-- ================================================
-- 補足1:
--   今回の CASE は検索 CASE であり、
--   真になった最初の WHEN の結果を返す。
--   どれも真でない場合は ELSE が無ければ NULL になる。  [oai_citation:7‡MySQL Developer Zone](https://dev.mysql.com/doc/refman/8.0/ja/flow-control-functions.html?utm_source=chatgpt.com)
-- ================================================


-- ================================================
-- 補足2:
--   今回の year 条件は
--     year <= 2001
--     year >= 2002
-- で全行をちょうどカバーしている。
--
--   そのため ELSE を書かなくても price が NULL にならない設計になっている。
--   これは与えられた year 範囲からの論理的な帰結である。
-- ================================================


-- ================================================
-- 補足3:
--   可読性の観点では、
--   「1つの表を見て1つの結果を返すだけ」の今回の処理は
--   CASE 版の方が意図を読み取りやすいことが多い。
--
--   一方で、条件ごとに取得行や結合先が大きく違う場合には、
--   UNION ALL で分けた方が分かりやすいこともある。
--   これは構文構造からの実務的な判断である。  [oai_citation:8‡MySQL Developer Zone](https://dev.mysql.com/doc/en/union.html?utm_source=chatgpt.com)
-- ================================================