-- ================================================
-- ファイル名: 09_select_population_case_aggregate.sql
-- 役割:
--   Population テーブルの縦持ちデータを、
--   CASE 式と SUM 集約を使って
--   都道府県ごとの男女別人口の横持ち形式へ変換する。
--
-- このSQLの目的:
--   先ほどの UNION による条件分岐版と同じ結果を、
--   1本の SELECT 文の中で表現すること。
--
-- 学習上の主題:
--   CASE 式による条件分岐
--   + 集約関数 SUM
--   + GROUP BY
--   を組み合わせて、
--   縦持ちデータを横持ちへ変換する方法を理解すること。
--
-- 今回の最重要ポイント:
--   UNION 版は
--     1. 男性集合を作る
--     2. 女性集合を作る
--     3. UNION で結合する
--     4. さらに GROUP BY でまとめ直す
--   という多段階構造だった。
--
--   一方、この CASE 集約版は
--     Population を読みながら
--     各行をその場で男性側・女性側へ振り分けて加算する
--   という 1 本の集約処理で表現している。
--
--   したがってアルゴリズムとしては、
--   UNION 版よりも「単純で、処理段数が少ない」形になりやすい。
--   これは実行計画の単純化につながる可能性がある。 [oai_citation:0‡MySQL Developer Zone](https://dev.mysql.com/doc/refman/8.0/ja/explain-output.html?utm_source=chatgpt.com)
-- ================================================

SELECT
    prefecture,
    -- prefecture:
    --   都道府県名である。
    --
    --   最後に GROUP BY prefecture を行うため、
    --   この列が結果の「1行を代表するキー」になる。
    --
    --   つまり最終結果は
    --     1都道府県 = 1行
    --   の横持ち表になる。

    SUM(
        CASE
            WHEN sex = '1' THEN pop
            ELSE 0
        END
    ) AS pop_men,
    -- SUM(CASE WHEN sex = '1' THEN pop ELSE 0 END) AS pop_men:
    --
    -- この式は、
    --   「男性行なら pop を加算し、
    --     それ以外の行なら 0 を加算する」
    -- という意味である。
    --
    -- 各行ごとに考えると、
    --
    --   sex = '1' の行
    --     → 男性人口として pop を採用する
    --
    --   sex = '2' の行
    --     → 男性人口には寄与しないので 0 を返す
    --
    -- その後 SUM で都道府県ごとに合計することで、
    -- 男性人口列 pop_men が完成する。
    --
    -- つまり
    --   CASE で「男性なら採用、女性なら0」
    --   SUM で「県ごとに合計」
    -- という二段構成で男性人口を作っている。
    --
    -- CASE 式は true になった最初の WHEN の結果を返し、
    -- ELSE が無ければ NULL になるが、
    -- 今回は ELSE 0 を入れているため、
    -- 非男性行は必ず 0 になる。 [oai_citation:1‡MySQL Developer Zone](https://dev.mysql.com/doc/refman/8.0/ja/flow-control-functions.html?utm_source=chatgpt.com)

    SUM(
        CASE
            WHEN sex = '2' THEN pop
            ELSE 0
        END
    ) AS pop_wom
    -- SUM(CASE WHEN sex = '2' THEN pop ELSE 0 END) AS pop_wom:
    --
    -- こちらは女性人口列を作る式である。
    --
    -- 各行ごとに
    --
    --   sex = '2' の行
    --     → 女性人口として pop を採用する
    --
    --   sex = '1' の行
    --     → 女性人口には寄与しないので 0 を返す
    --
    -- としてから、
    -- SUM によって都道府県ごとに合計する。
    --
    -- その結果、女性人口列 pop_wom が得られる。

FROM
    Population
    -- FROM Population:
    --   元データの人口表である。
    --
    --   この表は縦持ち形式で、
    --   1都道府県について
    --     男性行
    --     女性行
    --   が別々に存在する構造である。
    --
    --   今回の CASE 集約版では、
    --   この Population を 1 本の SELECT の中で直接処理している。
    --
    --   先ほどの UNION 版のように
    --   男性側 SELECT / 女性側 SELECT の 2 本へ分けていない。
    --
    --   そのため、構造上は
    --   「Population を読みながら、その場で男女別集計へ振り分ける」
    --   形になっている。

GROUP BY
    prefecture;
    -- GROUP BY prefecture:
    --   都道府県ごとに集約する。
    --
    --   これにより、
    --     徳島
    --     香川
    --     愛媛
    --     高知
    --     福岡
    --   ごとに1行の結果が返る。
    --
    --   つまり、縦持ちの男女別行データが
    --   横持ちの男女別人口表に変換される。


-- ================================================
-- このSQLの処理の流れ
-- ================================================
--
-- 1. Population テーブルの全行を読む
-- 2. 各行について sex の値を見る
-- 3. sex='1' ならその pop を男性人口側へ加算し、
--    sex='2' なら女性人口側へ加算する
-- 4. それを prefecture ごとに集約する
-- 5. 最終的に都道府県別の
--      pop_men
--      pop_wom
--    を返す
--
-- 概念的には次のような処理に近い。
--
--   group_by_prefecture = {}
--
--   for each row in Population:
--       if row.prefecture not in group_by_prefecture:
--           group_by_prefecture[row.prefecture] = {pop_men: 0, pop_wom: 0}
--
--       if row.sex == '1':
--           group_by_prefecture[row.prefecture].pop_men += row.pop
--       else:
--           group_by_prefecture[row.prefecture].pop_wom += row.pop
--
--   output group_by_prefecture
--
-- つまりこれは、
--   「Population を 1 回走査しながら、
--     行ごとに CASE 分岐して男女別の箱へ加算する」
--   というアルゴリズムである。
--
-- ここが UNION 版との最大の違いである。


-- ================================================
-- UNION 版とのアルゴリズム比較
-- ================================================
--
-- 先ほどの UNION 版は、概念的には次の流れだった。
--
--   1. Population から男性行だけを取り出す
--   2. Population から女性行だけを取り出す
--   3. UNION で結合する
--   4. その中間結果を GROUP BY でまとめ直す
--
-- つまり
--   分ける
--   結合する
--   再集約する
-- という多段階構造である。
--
-- 一方、今回の CASE 集約版は
--
--   1. Population を読む
--   2. 各行を CASE で男性側または女性側へ振り分ける
--   3. その場で集約する
--
-- という形であり、
--   UNION による中間表
--   UNION の結合段階
-- を持たない。
--
-- MySQL の EXPLAIN は、SELECT がどのように実行されるか、
-- どのテーブルをどの順序で読むかなどを示す。 [oai_citation:2‡MySQL Developer Zone](https://dev.mysql.com/doc/refman/8.0/ja/explain-output.html?utm_source=chatgpt.com)
--
-- また UNION は複数の query block を組み合わせる集合演算である。 [oai_citation:3‡MySQL Developer Zone](https://dev.mysql.com/doc/refman/8.0/ja/union.html?utm_source=chatgpt.com)
--
-- したがって構造的には、
--   UNION 版より CASE 集約版の方が
--   実行計画が単純になりやすく、
--   同じ表に対する条件分岐集約では有利になりやすい
-- と考えるのが自然である。これは構文構造からの妥当な推論である。 [oai_citation:4‡MySQL Developer Zone](https://dev.mysql.com/doc/refman/8.0/ja/explain-output.html?utm_source=chatgpt.com)
--
-- ただし、実際の速度は
--   行数
--   統計情報
--   インデックス
--   オプティマイザの判断
-- に依存するため、
-- 最終的な比較は EXPLAIN / EXPLAIN ANALYZE で確認するのが適切である。MySQL 8.0.18 以降には EXPLAIN ANALYZE もある。 [oai_citation:5‡MySQL Developer Zone](https://dev.mysql.com/doc/refman/8.0/en/mysql-nutshell.html?spm=a2c6h.13046898.publish-article.15.2c056ffaKTA1tv&utm_source=chatgpt.com)


-- ================================================
-- なぜ CASE 集約版が有利になりやすいのか
-- ================================================
--
-- アルゴリズム構造の違いを整理すると次のようになる。
--
-- 1. 参照回数
--   UNION 版:
--     Population を条件別に複数回扱う形になりやすい
--
--   CASE 版:
--     Population を 1 本の SELECT で扱う
--
-- 2. 中間結果
--   UNION 版:
--     男性側結果 + 女性側結果 + 中間表 TMP
--
--   CASE 版:
--     中間表を作らず、その場で集約しやすい
--
-- 3. 集約段数
--   UNION 版:
--     条件別抽出の後に再集約が必要
--
--   CASE 版:
--     最初から最終集約を行う
--
-- したがって、
--   「同じ表の行を性別で分けて、それぞれを別列へ入れたい」
-- だけなら、
--   CASE 集約版の方が処理段数が少ない
-- と考えやすい。
--
-- これが、主に UNION と比較したときのパフォーマンス上の論点である。


-- ================================================
-- 実行結果のイメージ
-- ================================================
--
-- Population の元データは次の通りである。
--
--   prefecture | sex | pop
--   -----------+-----+----
--   徳島       | 1   |  60
--   徳島       | 2   |  40
--   香川       | 1   |  90
--   香川       | 2   | 100
--   愛媛       | 1   | 100
--   愛媛       | 2   |  50
--   高知       | 1   | 100
--   高知       | 2   | 100
--   福岡       | 1   |  20
--   福岡       | 2   | 200
--
-- ここで各行に対して
--
--   男性側:
--     sex='1' なら pop, それ以外 0
--
--   女性側:
--     sex='2' なら pop, それ以外 0
--
-- を作ってから prefecture ごとに SUM すると、
-- 最終結果は次のようになる。
--
--   prefecture | pop_men | pop_wom
--   -----------+---------+--------
--   徳島       |  60     |  40
--   香川       |  90     | 100
--   愛媛       | 100     |  50
--   高知       | 100     | 100
--   福岡       |  20     | 200
--
-- つまり、UNION 版と同じ結果を、
-- より直接的な集約で得ている。


-- ================================================
-- 図解: CASE 集約版のアルゴリズム
-- ================================================
--
--   Population
--        |
--        v
--   1回だけ走査
--        |
--        v
--   各行ごとに CASE 評価
--        |
--        +---------------------------------------+
--        | sex='1' なら pop_men 側に pop を加算 |
--        | sex='2' なら pop_wom 側に pop を加算 |
--        +---------------------------------------+
--        |
--        v
--   GROUP BY prefecture
--        |
--        v
--   最終結果
--
-- つまり、
--   分けてから結合する
-- のではなく、
--   1回読みながらその場で振り分けて集約している。


-- ================================================
-- UNION 版との図解比較
-- ================================================
--
-- 1. UNION 版
--
--   Population
--      |
--      +-----------------------------+
--      |                             |
--      v                             v
--   sex='1' 抽出                 sex='2' 抽出
--      |                             |
--      v                             v
--   男性側結果                   女性側結果
--      |                             |
--      +-------------+---------------+
--                    |
--                    v
--                  UNION
--                    |
--                    v
--                 中間表 TMP
--                    |
--                    v
--            GROUP BY prefecture
--                    |
--                    v
--                 最終結果
--
--
-- 2. CASE 集約版
--
--   Population
--      |
--      v
--   1回走査
--      |
--      v
--   CASE で分岐しながら集約
--      |
--      v
--   GROUP BY prefecture
--      |
--      v
--   最終結果
--
-- この比較から、
--   CASE 集約版の方が段数が少なく、
--   アルゴリズム構造が単純
-- であることが分かる。


-- ================================================
-- 構文ごとの意味
-- ================================================
--
-- SELECT prefecture,
--        SUM(CASE WHEN sex = '1' THEN pop ELSE 0 END) AS pop_men,
--        SUM(CASE WHEN sex = '2' THEN pop ELSE 0 END) AS pop_wom
--   → 都道府県ごとの男女人口を横持ち列として返す
--
-- CASE WHEN sex = '1' THEN pop ELSE 0 END
--   → 男性行なら pop、そうでなければ 0 を返す
--
-- CASE WHEN sex = '2' THEN pop ELSE 0 END
--   → 女性行なら pop、そうでなければ 0 を返す
--
-- SUM(...)
--   → 県ごとにその値を合計する
--
-- FROM Population
--   → 元データは Population 表
--
-- GROUP BY prefecture
--   → 都道府県ごとに1行へ集約する
--
-- ;
--   → SQL文の終了を表す


-- ================================================
-- パフォーマンス比較の実務的な見方
-- ================================================
--
-- 一般論として、
--   同じ表に対する単純な条件分岐集約
-- であれば、
--   UNION 版より CASE 集約版
-- の方が選ばれやすい。
--
-- 理由は、
--   構造が単純
--   中間結果が少ない
--   参照がまとまりやすい
-- ためである。
--
-- ただし、SQL の性能は最終的には実行計画で判断すべきである。
--
-- MySQL では EXPLAIN が実行方法の確認に使え、
-- EXPLAIN ANALYZE では実際の実行情報も確認できる。 [oai_citation:6‡MySQL Developer Zone](https://dev.mysql.com/doc/refman/8.0/ja/explain-output.html?utm_source=chatgpt.com)
--
-- したがって本当に比較するなら、
--   UNION 版
--   CASE 集約版
-- の両方に EXPLAIN を付けて確認するのが正しい。


-- ================================================
-- 補足1:
--   今回の CASE は SELECT 句内の CASE operator であり、
--   true になった最初の WHEN の結果を返す。 [oai_citation:7‡MySQL Developer Zone](https://dev.mysql.com/doc/refman/8.0/ja/flow-control-functions.html?utm_source=chatgpt.com)
-- ================================================


-- ================================================
-- 補足2:
--   ELSE 0 を入れているのは、
--   SUM 集約時に「その性別ではない行は 0 として扱う」
--   ためである。
--
--   これにより、都道府県ごとの合計が自然に求まる。
-- ================================================


-- ================================================
-- 補足3:
--   可読性の面でも、
--   「性別ごとに人数を合計したい」だけなら
--   CASE 集約版の方が最終目的に直結していて分かりやすいことが多い。
--
--   一方、UNION 版は教材として
--   縦持ち→横持ち変換の過程を明示したいときには有用である。
-- ================================================